"""Builds game\\gamedata\\spawns\\all.spawn (lives in <root>\\src\\spawn\\):
  vanilla decompiled spawn (work\\spawn_soc\\all_soc from decompile_spawn.ps1, read-only) -> apply spawn_edits.py
  -> work\\spawn_build\\all_soc -> universal_acdc -compile -> game\\gamedata\\spawns\\all.spawn
Run with any Python 3 (Blender's bundled python.exe works):
  python build_spawn.py
"""
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spawnlib  # noqa: E402
import spawn_edits  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BASE = os.path.join(ROOT, "work", "spawn_soc", "all_soc")
BUILD = os.path.join(ROOT, "work", "spawn_build")
ACDC_DIR = next((os.path.join(dp) for dp, dn, fn in os.walk(os.path.join(ROOT, "tools")) if "universal_acdc.exe" in fn), None)
if ACDC_DIR is None:
    raise SystemExit("universal_acdc.exe not found under tools\\")
OUT = os.path.join(ROOT, "game", "gamedata", "spawns", "all.spawn")
HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    src_dir = os.path.join(BUILD, "all_soc")
    if os.path.isdir(BUILD):
        shutil.rmtree(BUILD)
    shutil.copytree(BASE, src_dir, ignore=shutil.ignore_patterns("*_compared.ltx"))

    report = ["# all.spawn changes", "",
              "Generated by build_spawn.py from spawn_edits.py. Do not edit by hand.", ""]
    levels = (set(spawn_edits.REMOVE) | set(spawn_edits.REMOVE_SECTIONS) | set(spawn_edits.STRIP_LOGIC)
              | set(spawn_edits.MODIFY) | set(spawn_edits.ADD))
    for level in sorted(levels):
        path = os.path.join(src_dir, "alife_%s.ltx" % level)
        pre, secs = spawnlib.parse(path)
        by_name = {name: why for name, why in spawn_edits.REMOVE.get(level, [])}
        by_section = spawn_edits.REMOVE_SECTIONS.get(level, {})
        strip = {name: why for name, why in spawn_edits.STRIP_LOGIC.get(level, [])}
        modify = spawn_edits.MODIFY.get(level, {})
        kept, removed, stripped, modified = [], [], [], []
        for s in secs:
            why = by_name.get(s.name) or by_section.get(s.section_name)
            if why:
                removed.append((s, why))
                continue
            if s.name in strip:
                s.remove_custom_data()
                stripped.append(s)
            for key, value in modify.get(s.name, {}).items():
                if key == "custom_data":
                    s.set_custom_data(value)
                else:
                    s.set(key, value)
            if s.name in modify:
                modified.append(s.name)
            kept.append(s)
        missing = ((set(by_name) - {s.name for s, _ in removed}) | (set(strip) - {s.name for s in stripped})
                   | (set(modify) - set(modified)))
        if missing:
            raise SystemExit("not found in %s: %s" % (level, ", ".join(sorted(missing))))
        # additions: clone a vanilla object by name, then override keys
        by_obj = {s.name: s for s in secs}
        next_header = max(int(s.header) for s in secs if s.header.isdigit()) + 1
        added = []
        for obj in spawn_edits.ADD.get(level, []):
            tpl = by_obj.get(obj["template"])
            if tpl is None:
                raise SystemExit("ADD template not found in %s: %s" % (level, obj["template"]))
            s = spawnlib.Section(str(next_header), list(tpl.lines))
            next_header += 1
            s.set("name", obj["name"])
            for key, value in obj.items():
                if key in ("template", "name"):
                    continue
                if key == "custom_data":
                    if value is None:
                        s.remove_custom_data()
                    else:
                        s.set_custom_data(value)
                else:
                    s.set(key, value)
            kept.append(s)
            added.append(obj["name"])
        spawnlib.write(path, pre, kept)
        report += ["## %s (%d removed)" % (level, len(removed)), "",
                   "| Object | Section | Position | Reason |", "|---|---|---|---|"]
        for s, why in sorted(removed, key=lambda r: (r[0].section_name, r[0].name)):
            p = s.position()
            report.append("| %s | %s | %.0f, %.0f, %.0f | %s |" % (
                s.name, s.section_name, p[0], p[1], p[2], why))
        report += ["", "### Kept, vanilla logic removed", ""]
        report += ["- %s: %s" % (s.name, strip[s.name]) for s in stripped]
        report += ["", "### Modified", ""] + ["- %s: %s" % (n, ", ".join(sorted(modify[n]))) for n in modified]
        report += ["", "### Added", ""] + ["- %s" % n for n in added]
        report.append("")
        print("%s: removed %d, stripped %d, kept %d" % (level, len(removed), len(stripped), len(kept)))

    with open(os.path.join(HERE, "REMOVED.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(report))

    for ini in ("clsids.ini", "convert.ini", "way_prefixes.ini"):
        shutil.copy(os.path.join(ACDC_DIR, ini), BUILD)
    new_spawn = os.path.join(BUILD, "all.spawn")
    r = subprocess.run([os.path.join(ACDC_DIR, "universal_acdc.exe"), "-compile", src_dir, "-out", new_spawn],
                       cwd=BUILD, capture_output=True, text=True)
    tail = (r.stdout + r.stderr).strip().splitlines()[-3:]
    print("\n".join(tail))
    if r.returncode != 0 or not os.path.exists(new_spawn):
        raise SystemExit("acdc compile failed")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    shutil.copy(new_spawn, OUT)
    print("installed", OUT, os.path.getsize(OUT))


if __name__ == "__main__":
    main()
